# .github/workflows/daily_digest.yml
name: Daily AI Digest

on:
  workflow_dispatch:
  schedule:
    - cron: '30 06 * * *'   # 07:30 CET

jobs:
  send-digest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11               # ← pin 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Run pipeline
        run: python src/pipeline.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:   ${{ secrets.CHAT_ID }}
      - name: Commit & push digest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add digests/*.md
          git commit -m "chore: archive digest $(date +%F)" || exit 0
          
          git remote set-url origin \
            "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"
          
          git push origin HEAD