# .github/workflows/daily_digest.yml
name: Daily AI Digest

on:
  workflow_dispatch:
  schedule:
    - cron: '30 06 * * *'   # 07:30 CET

jobs:
  send-digest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11               # ← pin 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Run pipeline
        run: python src/pipeline.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:   ${{ secrets.CHAT_ID }}