# .github/workflows/daily_digest.yml
name: “Daily AI Digest”

on:
  workflow_dispatch:
  schedule:
    # Runs at 06:30 UTC (07:30 CET) every day
    - cron: '* * * * *'

jobs:
  send-digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: python src/pipeline.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:   ${{ secrets.CHAT_ID }}